config/routes.rb
Rails.application.routes.draw do
  get 'task/view'
  resources :structures
  resources :problems
  resources :admin_teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "signup", to: "students#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :students, except: [:new]

  # Defines the root path route ("/")
  root 'admin_teachers#index'

  get 'task(/:id)', to: 'task#view', :as => :task
  get 'tasks/index', to: 'task#index'
  get 'task(/:id)/Representacion', to: 'task#represent_step'
  get 'task(/:id)/DCL', to: 'task#dcl_step'
  get 'task(/:id)/Ecuaciones', to: 'task#equation_step'

  get 'problem(/:id)/duplicated', to: 'problems#duplicate', as: 'duplicate'

  resources :responses
  post 'task(/:id)/Ecuaciones', to: 'task#equation_step_post_version'
  
end

app/models/structure.rb
require 'json'
class Structure < ApplicationRecord
    belongs_to :admin_teacher
    has_many :problems, dependent: :destroy
    [:nodes_list, :segments_list, :moment_reference, :force_values].each do |v|
        validates v, presence: true
    end    

    def get_nodes_json
        JSON.load(nodes_list)
    end

    def get_segments_json
        segments_json = []
        JSON.load(segments_list).each do |segment|
            if segment["iType"].include?("Seg")
                segments_json.push(segment)
            end
        end
        
        segments_json
    end

    def get_forces_json
        JSON.load(force_values)
    end

    def get_moment_json
        JSON.load(moment_values)
    end

    def get_node(tag)
        get_nodes_json.each do |node|
            if node["nombre"] == tag
                return node
            end
        end
    end

    def count_forces_moments
        if get_forces_json.present?
            get_forces_json.length() + get_moment_json.length()
        end
    end

    def get_supports
        supports = []
        if get_nodes_json.present?
            get_nodes_json.each do |node|
                if ![3,5,4,0].include?(node["tipo"])
                    supports.push(node)
                end
            end
        end
        supports
    end

    def support_count
        if get_supports.present?
            get_supports.length
        end
    end

    def has_support?(type)
        if get_supports.present?
            if type == "empotrado"
                get_supports.each do |support|
                    if support["tipo"] == 1
                        return true
                    end
                end
            elsif type == "deslizante"
                get_supports.each do |support|
                    if support["tipo"] == 2
                        return true
                    end
                end
            elsif type == "fijo"
                get_supports.each do |support|
                    if (6..9).include?(support["tipo"])
                        return true
                    end
                end
            end
        end
        return false
    end
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_structure, only: %i[ show edit update destroy ]

  # GET /structures or /structures.json
  def index
    @structures = Structure.all
  end

  # GET /structures/1 or /structures/1.json
  def show
  end

  # GET /structures/new
  def new
    @structure = Structure.new
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures or /structures.json
  def create
    @structure = Structure.new(structure_params)
    
    respond_to do |format|
      if @structure.save
        format.html { redirect_to structure_url(@structure), notice: "Structure was successfully created." }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /structures/1 or /structures/1.json
  def update
    respond_to do |format|
      if @structure.update(structure_params)
        format.html { redirect_to structure_url(@structure), notice: "Structure was successfully updated." }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /structures/1 or /structures/1.json
  def destroy
    @structure.destroy

    respond_to do |format|
      format.html { redirect_to structures_url, notice: "Structure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_structure
      @structure = Structure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def structure_params
      params.require(:structure).permit(:admin_teacher_id, :nodes_list, :segments_list, :struct_link, :force_values, :moment_values, :admin_teacher_id, :moment_reference)
    end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_form.html.erb
<%= form_with(model: structure) do |form| %>
  <% if structure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
        <% structure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :admin_teacher_id, style: "display: block" %>
    <%= form.number_field :admin_teacher_id %>
  </div>

  <div>
    <%= form.label :moment_reference, style: "display: block" %>
    <%= form.text_field :moment_reference %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/structures/_structure.html.erb
<div id="<%= dom_id structure %>">
  <p>
    <strong>Admin teacher:</strong>
    <%= structure.admin_teacher_id %>
  </p>

  <p>
    <strong>Moment reference:</strong>
    <%= structure.moment_reference %>
  </p>

</div>

app/views/structures/edit.html.erb
<h1>Editing structure</h1>

<%= render "form", structure: @structure %>

<br>

<div>
  <%= link_to "Show this structure", @structure %> |
  <%= link_to "Back to structures", structures_path %>
</div>

app/views/structures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Structures</h1>

<div id="structures">
  <% @structures.each do |structure| %>
    <%= render structure %>
    <p>
      <%= link_to "Show this structure", structure %>
    </p>
  <% end %>
</div>

<%= link_to "New structure", new_structure_path %>

app/views/structures/new.html.erb
<h1>New structure</h1>

<%= render "form", structure: @structure %>

<br>

<div>
  <%= link_to "Back to structures", structures_path %>
</div>

app/views/structures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @structure %>

<div>
  <%= link_to "Edit this structure", edit_structure_path(@structure) %> |
  <%= link_to "Back to structures", structures_path %>

  <%= button_to "Destroy this structure", @structure, method: :delete %>
</div>