config/routes.rb
Rails.application.routes.draw do
  get 'task/view'
  resources :structures
  resources :problems
  resources :admin_teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "signup", to: "students#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :students, except: [:new]

  # Defines the root path route ("/")
  root 'admin_teachers#index'

  get 'task(/:id)', to: 'task#view', :as => :task
  get 'tasks/index', to: 'task#index'
  get 'task(/:id)/Representacion', to: 'task#represent_step'
  get 'task(/:id)/DCL', to: 'task#dcl_step'
  get 'task(/:id)/Ecuaciones', to: 'task#equation_step'

  get 'problem(/:id)/duplicated', to: 'problems#duplicate', as: 'duplicate'

  resources :responses
  post 'task(/:id)/Ecuaciones', to: 'task#equation_step_post_version'
  
end

app/models/problem.rb
class Problem < ApplicationRecord
    belongs_to :admin_teacher
    belongs_to :structure
    has_one :task, dependent: :destroy
    has_many :steps, dependent: :destroy
    accepts_nested_attributes_for :structure
    has_one_attached :image, dependent: :destroy

    before_create :set_stats, :set_supports_points, :set_forces_points

    after_create :set_answers

    def set_answers
        Answer.create(step_id: @step1, content: (self.structure_id+1).to_s, answer_type: "a_structure_id")
        step3_xforces = [obtain_support_forces("x"),xy_force_vectors("x")].to_json
        step3_yforces = [obtain_support_forces("y"),xy_force_vectors("y")].to_json

        Answer.create(step_id: @step3, content: step3_xforces, answer_type: "xforces")
        Answer.create(step_id: @step3, content: step3_yforces, answer_type: "yforces")
        Answer.create(step_id: @step3, content: self.structure.get_moment_json, answer_type: "moment")
        Answer.create(step_id: @step4, content: make_xforce_ecuation, answer_type: "xforce")
        Answer.create(step_id: @step4, content: make_yforce_ecuation, answer_type: "yforce")
        Answer.create(step_id: @step4, content: make_moment_ecuation, answer_type: "moment_ecuation")
    end

    
    def step1=(step1)
        @step1 = step1
    end

    def step1
        @step1
    end

    def step3=(step3)
        @step3 = step3
    end

    def step3
        @step3
    end

    def step4=(step4)
        @step4 = step4
    end

    def step4
        @step4
    end

    def get_supports_points
        self.extern_joins_points
    end


    def set_supports_points
        supports_count = structure.support_count
        builtin = structure.has_support?("empotrado")
        slider = structure.has_support?("deslizante")
        fixed = structure.has_support?("fijo")
        if builtin && slider && fixed
            if supports_count == 3
                @difficulty_b = 50
            elsif supports_count >= 8
                @difficulty_b = 100
            elsif supports_count > 3
                @difficulty_b = 50 + ((supports_count-3) * 10)
            end
            self.extern_joins_points = @difficulty_b
        elsif builtin && slider || builtin && fixed || slider && fixed
            if supports_count == 2
                @difficulty_b = 30
            elsif supports_count >= 9
                @difficulty_b = 100
            elsif supports_count > 2
                @difficulty_b = 30 + ((supports_count-2) * 10)
            end
            self.extern_joins_points = @difficulty_b
        elsif builtin || slider || fixed
            if supports_count >= 10
                @difficulty_b = 100
            else
                @difficulty_b = supports_count * 10
            end
            self.extern_joins_points = @difficulty_b
        else
            self.extern_joins_points = 0
        end
        
    end

    def get_forces_points
        self.forces_moments_points
    end

    def set_forces_points
        if structure.count_forces_moments.present?
            forces_count = structure.count_forces_moments
            if forces_count >= 10
                @difficulty_f = 100
            end
            @difficulty_f = forces_count * 10
            self.forces_moments_points = @difficulty_f
        end
    end

    def obtain_support_forces(x_or_y)
        supports = structure.get_supports()
        xy_forces = []
        supports.each do |support|
            if support["tipo"] == 1 #empotrado
                xy_forces.push(support['nombre']+x_or_y)
            elsif support["tipo"] == 2
                if x_or_y == 'y'
                    xy_forces.push(support['nombre']+x_or_y) #deslizante
                end
            elsif (6..9).include?(support["tipo"]) #fijo
                xy_forces.push(support['nombre']+x_or_y)
            end
        end #filtrar en x e y y concatenar el x al nombre del punto o el y
        xy_forces
    end

    def xy_force_vectors(x_or_y)
        xy_force_vectors = structure.get_forces_json()
        x_forces = []
        y_forces = []
        xy_force_vectors.each do |xy_force|
            if x_or_y == 'x'
                if xy_force['Angulo'] != nil
                    x_forces.push(xy_force['Magnitud_o_distancia'].to_s + ' * ' + 'cos(' + xy_force['Angulo'].to_s + ')')
                end
            elsif x_or_y == 'y'
                if xy_force['Angulo'] != nil
                    y_forces.push(xy_force['Magnitud_o_distancia'].to_s + ' * ' + 'sin(' + xy_force['Angulo'].to_s + ')')
                end
            end
        end
        if x_or_y == 'x'
            return x_forces
        elsif x_or_y == 'y'
            return y_forces
        end
    end

    def make_xforce_ecuation()        
        x_support_forces = obtain_support_forces('x')
        x_force_vectors = xy_force_vectors('x')
        total_forces = x_support_forces + x_force_vectors
        forces_for_the_view = ''
        total_forces.each do |f|
            forces_for_the_view += ' + ' + f
        end
        forces_for_the_view
    end

    def make_yforce_ecuation()
        y_support_forces = obtain_support_forces('y')
        y_force_vectors = xy_force_vectors('y')
        total_forces = y_support_forces + y_force_vectors
        forces_for_the_view = ''
        total_forces.each do |f|
            forces_for_the_view += ' + ' + f
        end
        forces_for_the_view
    end

    def make_moment_ecuation()
        xy_moments = structure.get_moment_json()
        xy_forces = structure.get_forces_json()
        all_supports = structure.get_supports()
        nod_ref = structure.moment_reference
        pr_nodes = structure.get_nodes_json()
        dist_to_momentx = 0
        dist_to_momenty = 0
        all_support_m = []
        moment_xy = []

        nod_ref = pr_nodes.find{|e| e['nombre'] == nod_ref}

        xy_moments.each do |m|
            moment_xy.push(m['magnitude'].to_s)
        end

        xy_forces.each do |f|
            ss = f['iType'][7..7]
            cur_moment_node = pr_nodes.find{|e| e['nombre'] == ss}
            dist_to_momentx = (nod_ref['x'] - cur_moment_node['x']).abs
            dist_to_momenty = (nod_ref['y'] - cur_moment_node['y']).abs
            if dist_to_momentx == 0
                moment_xy.push('(' + f['Magnitud_o_distancia'].to_s + ' * ' + dist_to_momenty.to_s + ')')
            elsif dist_to_momenty == 0
                moment_xy.push('(' + f['Magnitud_o_distancia'].to_s + ' * ' + dist_to_momentx.to_s + ')')
            elsif dist_to_momentx != 0 && dist_to_momenty != 0
                moment_xy.push('(' + f['Magnitud_o_distancia'].to_s + ' * ' + (dist_to_momentx + dist_to_momenty).to_s + ')')
            end
        end

        all_supports.each do |sup|
            dist_to_momentx = (nod_ref['x'] - sup['x']).abs
            dist_to_momenty = (nod_ref['y'] - sup['y']).abs
            if dist_to_momentx == 0
                moment_xy.push('(' + dist_to_momenty.to_s + ' * ' + sup['nombre'] + 'y' + ')')
            elsif dist_to_momenty == 0
                moment_xy.push('(' + dist_to_momentx.to_s + ' * ' + sup['nombre'] + 'x' +')')
            elsif dist_to_momentx != 0 && dist_to_momenty != 0
                moment_xy.push('(' + dist_to_momentx.to_s + ' * ' + sup['nombre'] + 'x' + ' + ' + dist_to_momenty.to_s + sup['nombre'] + 'y' + ')')
            end
        end

        moment_for_view = ''
        moment_xy.each do |m|
            moment_for_view += ' + ' + m
        end
        moment_for_view
    end

    private
    def set_stats
        self.extern_joins_points = 0
        self.forces_moments_points = 0
        self.con_rod_points = 0
        self.ball_joint_points = 0
    end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :require_user
  before_action :set_problem, only: %i[ show edit update destroy ]

  # GET /problems or /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems or /problems.json
  def duplicate
    @problem1 = Problem.find(params[:id])
    @problem = @problem1.dup
    @problem.id = nil
  end

  # GET /problems/1 or /problems/1.json
  def show
    @current_steps = []
    Step.where(problem_id: @problem.id).each do |step|
      @current_steps.push(step.step_type)
    end
    @difficulty_b = @problem.get_supports_points
    @difficulty_f = @problem.get_forces_points
    @forces_ecuation_x = @problem.make_xforce_ecuation()#"10 ∗ cos(60°) + Bx + 5 + 8 ∗ cos(45°) = 0"
    @forces_ecuation_y = @problem.make_yforce_ecuation()#"−10 ∗ sin(60°) + By − 8 ∗ sin(45°) + Dy − 5 = 0"
    @moment_ecuation = @problem.make_moment_ecuation()#" 3 ∗ 10 ∗ sin(60°) − 1 − 1 ∗ 8 ∗ cos(45°) − 6 ∗ 8 ∗ sin(45°) − 9 ∗ 5 + 1 ∗ 5 + 11 ∗ Dy"
  end

  # GET /problems/new
  def new
    @admin_teacher = AdminTeacher.first
    @new_structure = Structure.new
    if Problem.first.present?
      @title = "Problem #" + (Problem.last.id + 1).to_s
    else
      @title = "Problem #1" 
    end
    @structure = Structure.new
    @problem = Problem.new
    @problem.build_structure
  end

  # GET /problems/1/edit
  def edit
    @title = "Problem #" + (@problem.id).to_s
  end

  # POST /problems or /problems.json
  def create
    
    @problem = Problem.new(problem_params)
    some_null_values = false
    temporal = JSON.load(problem_params['structure_attributes']['force_values'])
    temporal.each do |t|
      if t["Magnitud_o_distancia"] == nil || t["Angulo"] == nil
        some_null_values = true
      end
    end
    

    respond_to do |format|
      if (@problem.step1 != "1" && @problem.step3 != "1" && @problem.step4 != "1") || some_null_values == true
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      else
        if @problem.save
          if @problem.step1 == "1"
            @step1 = Step.new(title: nil, description: "nn", step_type: "Representacion", problem_id: @problem.id)
            @step1.save
          end  
          
          if @problem.step3 == "1"
            @step3 = Step.new(title: nil, description: "nn", step_type: "DCL", problem_id: @problem.id)
            @step3.save
          end
      
          if @problem.step4 == "1"
            @step4 = Step.new(title: nil, description: "nn", step_type: "Ecuaciones", problem_id: @problem.id)
            @step4.save
          end        

          # create_an_asociated_task(@problem)
          
          format.html { redirect_to problem_url(@problem), notice: "Problem was successfully created." }
          format.json { render :show, status: :created, location: @problem }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /problems/1 or /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to problem_url(@problem), notice: "Problem was successfully updated." }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1 or /problems/1.json
  def destroy
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url, notice: "Problem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problem_params
      params.require(:problem).permit(
        :admin_teacher_id, 
        :title, 
        :description, 
        :extern_joins_points, 
        :forces_moments_points,
        :con_rod_points, 
        :ball_joint_points, 
        :image, 
        :step1,
        :step3,
        :step4,
        structure_attributes: [:nodes_list, :segments_list, :struct_link, :force_values, :moment_values, :admin_teacher_id, :moment_reference]
      )
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_dificulty.html.erb
<h3>Dificultad</h3>
<%
=begin%>
 <h4>Biela</h4>
<div class="progress progress-striped">
    <div class="progress-bar progress-bar-info" role="progressbar"
        aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"
        style="width: 0%">
    <span class="sr-only">20% completado</span>
    </div>
</div>
<h4>Rotula</h4>
<div class="progress progress-striped">
    <div class="progress-bar progress-bar-info" role="progressbar"
        aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"
        style="width: 0%">
    <span class="sr-only">20% completado</span>
    </div>
</div> 
<%
=end%>
<h4>Apoyos</h4>
<div class="progress">
    <div class="progress-bar progress-bar-striped" role="progressbar"
        aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"
        style="width: <%= difficulty_b %>%">
    </div>
</div>
<br />
<h4>Fuerzas</h4>
<div class="progress">
    <div class="progress-bar progress-bar-striped" role="progressbar"
        aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"
        style="width: <%= difficulty_f %>%">
    </div>
</div>

app/views/problems/_form.html.erb
<%= form_with(model: problem) do |form| %>
  <% if problem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
        <% problem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :admin_teacher_id, :value => 1 %>

  <div class="field">
    <%= form.label "Titulo", style: "display: block" %>
    <%= form.text_field :title, style: "width:70%", :value => @title %>
  </div>
<br>
<br>
  <div class="field">
    <% if @problem.image.attached? %>
      <%= image_tag @problem.image, style: "width: 600px; display: block"%>
    <% end %>

    <%= form.label "Subir Imagen del Problema" %>
    <%= form.file_field :image, class: "form-control", style: "width:70%"%>
  </div>
<br>
  <div class="field">
    <%= form.label "Enunciado", style: "display: block" %>
    <%= form.text_area :description, style: "width:70%" %>
  </div>
<br>
  <div class="field">
    
    <p>
    <h2>Instrucciones</h2>
    <br />
    <body>
    <div class="row">
        <div class="column1">
          Simbolos:<br />
          <%= image_tag("instructions/simbolos.jpg", width: "500px") %><br />   
        </div>
        <div class="column1">
            Fuerza:<br />
            <%= image_tag("instructions/fuerza.jpg", width: "500px") %><br />
            
            
        </div>
    </div>
    <br />
    <div class="row">
        <div class="column2 left">
            Rotula:<br />
            <%= image_tag("instructions/rotula.jpg", width: "250px") %><br />
            <br />
            Momento:<br />
            <%= image_tag("instructions/momento.jpg", width: "250px") %><br />
            <br />
        </div>
        <div class="column2 middle">
            Biela:<br />
            <%= image_tag("instructions/biela.jpg", width: "250px") %><br />
            <br />
            Apoyo deslizante:<br />
            <%= image_tag("instructions/apoyo_deslizante.jpg", width: "250px") %><br />
            <br />
        </div>
        <div class="column2 right">
            Apoyo Empotrado:<br />
            <%= image_tag("instructions/empotrado.jpg", width: "250px") %><br />
            <br />
            Apoyo fijo:<br />
            <%= image_tag("instructions/apoyo_fijo.jpg", width: "250px") %><br />
            <br />
        </div>
    </div>
    <br />
    <%= form.label "Dibujar el diagrama para un DCL", style: "display: block" %>
 </body>
    
    <div id="ggb-element"></div> 
<br>
    <%= render "steps", form: form %>

    <br><h3>Parametros de la Estructura</h3><br>
    <%= form.fields_for :structure do |s| %>
      <div class="field">
        <%= s.label "Listado de Nodos" %><br />
        <%= s.text_area :nodes_list, id: "myNodes", style: "width:70%"%>
      </div>
      <br>
      <div class="field">
        <%= s.label "Listado de segmentos" %><br />
        <%= s.text_area :segments_list, id: "mySegments", style: "width:70%" %>
      </div>
      <br>
      <div class="field">
        <%= s.label "Nodo de referencia momentos" %> <br />
        <%= s.text_area :moment_reference, id: "myMomentReferences", style: "width:70%"%>
      </div>
      <br>
      <div class="field">
        <%= s.label "Listado de fuerzas" %><br />
        <%= s.text_area :force_values, id: "myForceValues", style: "width:70%" %>
      </div>
      <br>
      <div class="field">
        <%= s.label "Listado de momentos" %><br />
        <%= s.text_area :moment_values, id: "myMomentumValues", style: "width:70%" %>
      </div> 
      <%= s.hidden_field :struct_link, id: "mySavedLink", style: "width:70%" %>
      <%= s.hidden_field :admin_teacher_id, :value => 1 %>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_import_module_tag "packs/geogebra_edit" %>

app/views/problems/_form_copy.html.erb
<%= form_with(model: problem) do |form| %>
  <% if problem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
        <% problem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :admin_teacher_id, :value => 1 %>

  <div class="field">
    <%= form.label "Titulo", style: "display: block" %>
    <%= form.text_field :title, style: "width:70%", :value => @title %>
  </div>
<br>
<br>
  <div class="field">
    <% if @problem.image.attached? %>
      <%= image_tag @problem.image, style: "width: 600px; display: block"%>
    <% end %>

    <%= form.label "Subir Imagen del Problema" %>
    <%= form.file_field :image, class: "form-control", style: "width:70%"%>
  </div>
<br>
  <div class="field">
    <%= form.label "Enunciado", style: "display: block" %>
    <%= form.text_area :description, style: "width:70%" %>
  </div>
<br>
  <div class="field">
    <%= form.label "Dibujar el diagrama para un DCL", style: "display: block" %>
    <p>
    <br />
    Circulo para nodos<br />
    Circulo sin relleno para apoyo deslizante<br />
    Triangulo para apoyo fijo<br />
    rombo relleno para rotula<br />
    rombo sin relleno para biela<br />
    X para empotrado<br />
    + para momento<br />
    </p>

    <div id="ggb-element"></div> 
<br>
    <%= render "steps", form: form %>

    <br><h3>Parametros de la Estructura</h3><br>
    <%= form.fields_for :structure do |s| %>
      <div class="field">
        <%= s.label "Listado de Nodos" %><br />
        <%= s.text_area :nodes_list, id: "myNodes", style: "width:70%"%>
      </div>
      <br>
      <div class="field">
        <%= s.label "Listado de segmentos" %><br />
        <%= s.text_area :segments_list, id: "mySegments", style: "width:70%" %>
      </div>
      <br>
      <div class="field">
        <%= s.label "Nodo de referencia momentos" %> <br />
        <%= s.text_area :moment_reference, id: "myMomentReferences", style: "width:70%"%>
      </div>
      <br>
      <div class="field">
        <%= s.label "Listado de fuerzas" %><br />
        <%= s.text_area :force_values, id: "myForceValues", style: "width:70%" %>
      </div>
      <br>
      <div class="field">
        <%= s.label "Listado de momentos" %><br />
        <%= s.text_area :moment_values, id: "myMomentumValues", style: "width:70%" %>
      </div> 
      <%= s.hidden_field :struct_link, id: "mySavedLink", style: "width:70%" %>
      <%= s.hidden_field :admin_teacher_id, :value => 1 %>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_import_module_tag "packs/geogebra_edit" %>

app/views/problems/_problem.html.erb
<div id="<%= dom_id problem %>">
  <p>
    <strong>Title:</strong>
    <%= problem.title%>
  </p>

  <% if problem.image.attached? %>
    <p>
      <%= image_tag problem.image, width: '100%', height: '100%'%>
    </p>
  <% end %>

  <p>
    <strong>Enunciado:</strong>
    <%= problem.description %>
  </p>

  <p>
    <strong>Nodo de Referencia Momentos:</strong>
    <%= problem.structure.moment_reference %>
  </p>

  <p>
    <strong>Listado de Fuerzas:</strong>
    <%= problem.structure.force_values %>
  </p>

  <p>
    <strong>Listado de Momentos:</strong>
    <%= problem.structure.moment_values %>
  </p>

  <p>
    <div id="applet_container" ></div>
  </p>

</div>

app/views/problems/_problem_resume.html.erb
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <% if problem.image.attached? %>
            <%= image_tag problem.image, width: '50%', class:"card-img-top", style: "height: 225px; width: 100%; display: block;" %>
        <% end%>
        <div class="card-body">
            <h4 class="mt-5">Tarea <%= problem.title %></h4>
            <p class="card-text"><%=  problem.description %></p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <%= link_to "Revisar", problem %>   &nbsp; | &nbsp;
                    <%= link_to 'Duplicar', duplicate_path(problem.id) %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/problems/_steps.html.erb
<h3>Pasos</h3>
<div>
    <td>
        <%= form.check_box :step1 %>
        Representacion<br>   
    </td>
    <td>
        <%= form.check_box :step3 %>
        DCL<br>    
    </td>
    <td>
        <%= form.check_box :step4 %>
        Ecuaciones<br>    
    </td>
</div>

app/views/problems/duplicate.html.erb
<div class="jumbotron text-center">
  <h2>Duplicate problem</h2> 
</div>

<div class="container">
  <%= render "form_copy", problem: @problem %>
  <br>
  <div>
    <td>   
      <%= link_to "Back to problems", problems_path, :class => "btn btn-primary" %>
    </td>
  </div>
</div>

<div id="base64_id" base64=<%= @problem.structure.struct_link%> ></div>
<%= javascript_import_module_tag "packs/geogebra_edit_current_problem" %>

app/views/problems/edit.html.erb
<div class="jumbotron text-center">
  <h2>Editing problem</h2> 
</div>

<div class="container">
  <%= render "form", problem: @problem %>
  <br>
  <div>
    <td>   
      <%= link_to "Show this problem", @problem, :class => "btn btn-primary" %> 
      <%= link_to "Back to problems", problems_path, :class => "btn btn-primary" %>
    </td>
  </div>
</div>

<div id="base64_id" base64=<%= @problem.structure.struct_link%> ></div>
<%= javascript_import_module_tag "packs/geogebra_edit_current_problem" %>

app/views/problems/index.html.erb
<br />
<div class="jumbotron text-center">
  <h2>Problems</h2> 
</div>
<br />

<div class="container">
    <div class="row">
        <% @problems.each do |problem| %>
            <%= render "problem_resume", problem: problem %>
        <% end %>
    </div>
</div>

<div class="container">
  <td>
    <%= link_to "New problem", new_problem_path, :class => "btn btn-primary" %>    
  </td>
</div>

app/views/problems/new.html.erb
<head>
    <meta name=viewport content="width=device-width,initial-scale=1">  
    <meta charset="utf-8"/>
</head>

<div class="jumbotron text-center">
  <h2>New problem</h2> 
</div>

<div class="container">
  <%= render "form", problem: @problem %>
  <br>
  <div>
    <td>
      <%= link_to "Back to problems", problems_path, :class => "btn btn-primary" %>    
    </td>
  </div>
</div>

app/views/problems/show.html.erb
<div class="jumbotron text-center">
   <h2>Problems</h2>
</div>

<div class="container">
  <p style="color: green"><%= notice %></p>
  <br />
  <h3> Problem Id: <%= @problem.id %></h3>
  <%= render @problem %>
  <%= render "dificulty", difficulty_b: @difficulty_b, difficulty_f: @difficulty_f  %>
  <br />
  <h3>Ecuaciones</h3>
  <em>ΣFx = <%= @forces_ecuation_x %></em><br>
  <em>ΣFy = <%= @forces_ecuation_y %></em><br>
  <em>ΣM = <%= @moment_ecuation %></em><br>
  <h3>Pasos</h3>
  <em><%= @current_steps.to_s %></em><br>
  <div><br>
    <%= link_to "Edit problem", edit_problem_path(@problem) %>
  </div>
  <br>
  
  <%= button_to "Delete problem", @problem, method: :delete, :class => "btn btn-danger" %>

</div>

<div id="base64_id" base64=<%= @problem.structure.struct_link%> ></div>

<%= javascript_import_module_tag "packs/geogebra_show" %>