config/routes.rb
Rails.application.routes.draw do
  get 'task/view'
  resources :structures
  resources :problems
  resources :admin_teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "signup", to: "students#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :students, except: [:new]

  # Defines the root path route ("/")
  root 'admin_teachers#index'

  get 'task(/:id)', to: 'task#view', :as => :task
  get 'tasks/index', to: 'task#index'
  get 'task(/:id)/Representacion', to: 'task#represent_step'
  get 'task(/:id)/DCL', to: 'task#dcl_step'
  get 'task(/:id)/Ecuaciones', to: 'task#equation_step'

  get 'problem(/:id)/duplicated', to: 'problems#duplicate', as: 'duplicate'

  resources :responses
  post 'task(/:id)/Ecuaciones', to: 'task#equation_step_post_version'
  
end

app/models/admin_teacher.rb
class AdminTeacher < ApplicationRecord
    has_secure_password
    has_many :problems, dependent: :destroy
end

app/controllers/admin_teachers_controller.rb
class AdminTeachersController < ApplicationController
  before_action :require_user
  before_action :set_admin_teacher, only: %i[ show edit update destroy ]


  # GET /admin_teachers or /admin_teachers.json
  def index
    @admin_teachers = AdminTeacher.all
  end

  # GET /admin_teachers/1 or /admin_teachers/1.json
  def show
  end

  # GET /admin_teachers/new
  def new
    @admin_teacher = AdminTeacher.new
  end

  # GET /admin_teachers/1/edit
  def edit
  end

  # POST /admin_teachers or /admin_teachers.json
  def create
    @admin_teacher = AdminTeacher.new(admin_teacher_params)

    respond_to do |format|
      if @admin_teacher.save
        format.html { redirect_to admin_teacher_url(@admin_teacher), notice: "Admin teacher was successfully created." }
        format.json { render :show, status: :created, location: @admin_teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_teachers/1 or /admin_teachers/1.json
  def update
    respond_to do |format|
      if @admin_teacher.update(admin_teacher_params)
        format.html { redirect_to admin_teacher_url(@admin_teacher), notice: "Admin teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_teachers/1 or /admin_teachers/1.json
  def destroy
    @admin_teacher.destroy

    respond_to do |format|
      format.html { redirect_to admin_teachers_url, notice: "Admin teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_teacher
      @admin_teacher = AdminTeacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_teacher_params
      params.require(:admin_teacher).permit(:full_name, :password)
    end
end

app/helpers/admin_teachers_helper.rb
module AdminTeachersHelper
end

app/views/admin_teachers/_admin_teacher.html.erb
<div id="<%= dom_id admin_teacher %>">
  <p>
    <strong>Full name:</strong>
    <%= admin_teacher.full_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= admin_teacher.email %>
  </p>

</div>

app/views/admin_teachers/_form.html.erb
<%= form_with(model: admin_teacher) do |form| %>
  <% if admin_teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_teacher.errors.count, "error") %> prohibited this admin_teacher from being saved:</h2>

      <ul>
        <% admin_teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>
  <br>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_teachers/edit.html.erb
<div class="jumbotron text-center">
  <h2>Editing admin teacher</h2> 
</div>

<div class="container">
  <%= render "form", admin_teacher: @admin_teacher %>
  <br>
  <div>
    <td>   
      <%= link_to "Show this admin teacher", @admin_teacher, :class => "btn btn-primary" %> 
      <%= link_to "Back to admin teachers", admin_teachers_path, :class => "btn btn-primary" %>
    </td>
  </div>
</div>

app/views/admin_teachers/index.html.erb
  
<div class="jumbotron text-center">
  <h2>Admin Teacher</h2> 
</div>
  
<div id="admin_teachers">
  
  <div class="container">
    <div class="row">
      <% @admin_teachers.each do |admin_teacher| %>
        <div class="col-sm-4">
          <%= render admin_teacher %>
          <p>
          <%= link_to "Show this admin teacher", admin_teacher %>
          </p>
          <br>
        </div>
      <% end %>   
    </div>
  </div>
</div>

<div class="container">
  <td>
    <%# <%= link_to "New admin teacher", new_admin_teacher_path, :class => "btn btn-primary" %>
  </td>
</div>

</body>
</html>

app/views/admin_teachers/new.html.erb
<div class="jumbotron text-center">
  <h2>New admin teacher</h2> 
</div>

<div class="container">
  <%= render "form", admin_teacher: @admin_teacher %>
  <br>
  <div>
    <td>
      <%= link_to "Back to admin teachers", admin_teachers_path, :class => "btn btn-primary" %>    
    </td>
  </div>
</div>

app/views/admin_teachers/show.html.erb
<div class="jumbotron text-center">
  <h2>Admin Teacher</h2>
</div>

<div class="container">
<p style="color: green"><%= notice %></p>
<h3> Teacher N°: <%= @admin_teacher.id %></h3>
<%= render @admin_teacher %>

<br>
</div>