config/routes.rb
Rails.application.routes.draw do
  get 'task/view'
  resources :structures
  resources :problems
  resources :admin_teachers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "signup", to: "students#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :students, except: [:new]

  # Defines the root path route ("/")
  root 'admin_teachers#index'

  get 'task(/:id)', to: 'task#view', :as => :task
  get 'tasks/index', to: 'task#index'
  get 'task(/:id)/Representacion', to: 'task#represent_step'
  get 'task(/:id)/DCL', to: 'task#dcl_step'
  get 'task(/:id)/Ecuaciones', to: 'task#equation_step'

  get 'problem(/:id)/duplicated', to: 'problems#duplicate', as: 'duplicate'

  resources :responses
  post 'task(/:id)/Ecuaciones', to: 'task#equation_step_post_version'
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">DCLITS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <% if teacher_logged_in? %>
                <li class="nav-item">
                    <%= link_to "Admin Teacher", admin_teachers_url, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Problems Available", problems_url, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Students", students_url, class: "nav-link" %>
                </li>
            <% end %>
            <% if student_logged_in? %>
                <li li class="nav-item">
                    <%= link_to "Tareas", "/tasks/index", method: "get", class: "nav-link" %>
                </li>
                <li li class="nav-item">
                    <%= link_to "Perfil", @current_student, class: "nav-link" %>
                </li>
            <% end %>
            <% if logged_in? %>
                <li li class="nav-item">
                    <%= link_to "Log out", logout_path, method: "delete", class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DclItsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <script type="text/javascript" src="https://www.geogebra.org/apps/deployggb.js"></script>
  

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <style>
    {
        box-sizing: border-box;
    }
    /* Set additional styling options for the columns*/
    .column1 {
    float: left;
    width: 50%;
    }

    .row:after {
    content: "";
    display: table;
    clear: both;
    }
    </style>

    <style>
    {
        box-sizing: border-box;
    }
    /* Set additional styling options for the columns */
    .column2 {
    float: left;
    }

    /* Set width length for the left, right and middle columns */
    .left {
    width: 33%;
    }

    .middle {
    width: 33%;
    }
    
    .right {
    width: 33%;
    }

    .row:after {
    content: "";
    display: table;
    clear: both;
    }
    </style>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <main role="main" class="container">

      <div class="starter-template">
        <%= yield %>
      </div>

    </main>
  </body>
</html>